# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rooms.Profile'),
            preserve_default=False,
        ),
    ]
